// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// import { application } from "./application"

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)


// Import and register all your controllers from the importmap under controllers/*

import { application } from "controllers/application"

// Eager load all controllers defined in the import map under controllers/**/*_controller
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)
eagerLoadControllersFrom("controllers", application)
